# Generated by Django 5.0.1 on 2024-01-31 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_business_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customer'),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.location'),
        ),
    ]
