# Generated by Django 5.0.1 on 2024-02-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_business_customer_alter_business_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business_Category',
            new_name='BusinessCategory',
        ),
    ]
